language: android
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      ant
      phablet-tools
env:
 global:
    - ANDROID_TARGET=android-29
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
android:
  licenses:
    - '.+'
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-google-google_play_services
    - extra-android-support
    - extra
    
before_script:
    - mkdir ~/bin
    - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo ~/bin/repo
    - chmod a+x ~/bin/repo
    - repo init -u https://github.com/palmbeach05/android-3 -b lineage-16.0
    - repo sync
    - git clone http://github.com/palmbeach05/local_manifests .repo/local_manifests -b master

script:
    - chmod +x gradlew
    - ./gradlew assembleDebug
    - ./gradlew assembleDebugAndroidTest    
    - ./gradlew build check
