language: android
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      ant
env:
 global:
    - ANDROID_TARGET=android-29
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
android:
  licenses:
    - '.+'
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-google-google_play_services
    - extra-android-support
    - extra
    
before_script:
    # Prepare pre-accepted licenses to not be promted at installation
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./google-licenses/* "$ANDROID_HOME/licenses/"

    # Download and install gcloud cli to run firebase test commands
    - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-218.0.0-linux-x86.tar.gz
    - tar zxf google-cloud-sdk-218.0.0-linux-x86.tar.gz google-cloud-sdk
    - echo n | ./google-cloud-sdk/install.sh
    - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file dir-to-your-service-account-key.json
    - ./google-cloud-sdk/bin/gcloud config set project your-project
    - echo y | ./google-cloud-sdk/bin/gcloud components update
    - echo y | ./google-cloud-sdk/bin/gcloud components install beta

script:
    - chmod +x gradlew
    - ./gradlew assembleDebug
    - ./gradlew assembleDebugAndroidTest    
    - ./gradlew build check
